dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, src/components/forms/ResourceGroupForm.js, storybook/package-lock.json, storybook/src/stories/Forms/ResourceGroupForm.stories.js
- `props.create` => `props.use_data`
=> Craig 64: Resource Group Form Updates

README.md, package.json
added public storybook at http://ibm.github.io/icse-react-assets
=> storybook now public

dist/index.cjs.js, dist/index.esm.js, src/components/forms/TransitGatewayForm.js, storybook/src/stories/Forms/TransitGateway.stories.js
https://github.ibm.com/Jennifer-Valle/CRAIG/issues/73
=> Issue 73: update data for transit gateway

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/KeyManagementForm.js
- toggleFieldName `use_data` in kms
=> fix: now has toggleFieldName

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/SecurityGroupForm.js, storybook/src/stories/Forms/SecurityGroupForm.stories.js
https://github.ibm.com/Jennifer-Valle/CRAIG/issues/70
=> remove isTeleport & vpc_name -> vpc

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, src/components/forms/SecretsManagerForm.js, storybook/src/stories/Forms/SecretsManager.stories.js
https://github.ibm.com/jennifer-valle/craig/issues/76
=> Secrets Manager 

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/SshKeyForm.js, storybook/src/stories/Forms/SshKeyForm.stories.js
- key callback didn't pass componentProps - required
- key callback description in story was wrong
=> fix key callback and story

dist/index.cjs.js, dist/index.esm.js, package.json, playground/src/App.js, src/components/forms/TransitGatewayForm.js, storybook/src/stories/Forms/TransitGateway.stories.js
- tgw connections was just using an array of vpc names which did not fit with new schema which is an array of objects
- modified tgw form to save connections array to state as 
```js
{ tgw: this.state.name, vpc: <vpc name>}
```
=> fix: tgw connections array

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/TransitGatewayForm.js
- last pr swapped name/id which broke saving
=> fix: rg name/id

dist/index.cjs.js, dist/index.esm.js, package.json, playground/src/App.js, src/components/Buttons.js, src/components/component-utils.js, src/components/forms/ClusterForm.js, src/components/forms/VpeForm.js, src/components/forms/VpnGatewayForm.js, src/components/forms/VsiForm.js, src/components/forms/WorkerPoolForm.js, src/index.css, storybook/src/stories/Buttons/SaveAddButton.stories.js, storybook/src/stories/Forms/ClusterForm.stories.js, storybook/src/stories/Forms/NetworkingRuleOrderCard.stories.js, storybook/src/stories/Forms/Subnets/SubnetTierForm.stories.js, storybook/src/stories/Forms/VpeForm.stories.js, storybook/src/stories/Forms/Vpn.stories.js, storybook/src/stories/Forms/VsiForm.stories.js, storybook/src/stories/Forms/WorkerPoolForm.stories.js
- added function `getSubnetList` to `component-utils` which will bind a function to any component that accepts `subnetList` as a prop to get the correct list of subnets based off of its state (this was done to reduce repeated code)
- all components that use subnetList have had `this.props.subnetList` replaced with `this.getSubnetList()` 
- all stories have been updated
- added `customIcon` to `SaveAddButton`, updated story
- updated version to 0.2.0
- fixed props on networkRuleOrderCard which were keeping story from rendering
=> fix: subnetList from props, feat: customIcon for button

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/Buttons.js, src/components/forms/NetworkingRulesOrderCard.js
- rules now base subForm/formInSubform on if sg rule or not - if sg, white, if nacl, grey. should be the only two cases now that vsi sg is gone
- fixed warning for customicon
=> fix rule styling + button warning

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/VpcForm.js
- toggling pgw no longer modifies props
=> fix: public gateways

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, src/components/forms/IamAccountSettingsForm.js
This PR resolves the CRAIG Warning: 
> Warning: Failed prop type: Invalid prop `data.restrict_create_service_id` of value `NOT_SET` supplied to  `IamAccountSettingsForm`, expected one of ["Unset","Yes","No"].
=> Define proptypes for restrict_create_service_id & restrict_create_platform_apikey using map (not forEach)

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/WorkerPoolForm.js, storybook/src/stories/Forms/WorkerPoolForm.stories.js
- event.selectedItems doesn't exist - was returning undefined on change instead of setting subnets
=> fix: subnets in workerpoolform

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/EventStreamsForm.js, storybook/src/stories/Forms/EventStreamsForm.stories.js
typo in EventStreamsForm props: `endpoint` changed to `endpoints`
=> Craig 110 2

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, playground/package-lock.json, src/components/forms/VpeForm.js, storybook/package-lock.json, storybook/src/stories/Forms/VpeForm.stories.js
- changed vpc name input to dropdown
- added prop vpcList for vpc
- changed formName to be `this.props.data.name + "-vpe" + this.state.vpc`
- updated vpeForm stories with changes
=> bug fix: vpc dropdown on vpe form (Issue 171)

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, src/components/forms/ObjectStorageBucketForm.js, storybook/package-lock.json, storybook/src/stories/Forms/ObjectStorage/ObjectStorageBucketForm.stories.js
https://github.ibm.com/Jennifer-Valle/CRAIG/issues/118
=> Add encryption key filter to object storage bucket form

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, playground/src/App.js, src/components/forms/ClusterForm.js, src/components/forms/VpeForm.js, src/lib/form-utils.js, storybook/package-lock.json
- fixed vpeForm to clear subnet & security_group lists when changing vpc dropdown
=> vpeForm Hotfix

dist/index.cjs.js, dist/index.esm.js, package.json, playground/src/App.js, src/components/MultiSelects.js, src/components/forms/AtrackerForm.js, src/components/forms/F5VsiForm.js, src/components/forms/IamAccountSettingsForm.js, src/components/forms/ObjectStorageForm.js, src/components/forms/SubnetForm.js, src/components/forms/SubnetTileForm.js, src/components/forms/VsiForm.js, storybook/src/stories/Forms/F5VsiForm.stories.js, storybook/src/stories/Forms/VsiForm.stories.js
=> craig 167: vsi form bugs

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, src/components/forms/F5VsiForm.js, storybook/package-lock.json, storybook/src/stories/Forms/F5VsiForm.stories.js
- changed F5 Image Dropdown to be an array variable in `F5VsiForm`
- changed story to include array variable and used [updated image list](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/bd308c7c84bbfa199fb4c791c69a5bb43c527ce2/f5_vsi.tf) for example
- changed build to 0.3.16
=> F5VsiForm: F5 Image Dropdown Variable Hotfix

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/SecretsManagerForm.js
- removed use secrets manager from state of secrets manager form
=> remove use secrets manager

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/IcseFormTemplate.js, storybook/src/stories/DynamicComponents/IcseFormTemplate.stories.js
- forceOpen not passed to form template, needed for implementation of forceShowForm to force forms open when fields are invalid
=> add forceopen to form template

dist/index.cjs.js, dist/index.esm.js, package.json
will look into adding build command to a git hook
=> Hotfix build

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/F5VsiForm.js
- zones need to be a number not a string in state
- use spread operator
=> hotfix: zones now number, use spread

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/F5VsiForm.js, storybook/src/stories/Forms/F5VsiForm.stories.js
- f5 field names were inconsistent with schema, updated
- machine_type -> profile, f5_image_name -> image,  boot_volume_encryption_key_name -> encryption_key
=> fix f5 field names

dist/index.cjs.js, dist/index.esm.js, package.json, src/lib/f5-utils.js, unit-tests/f5-utils.test.js
urls are now optional for validation, needed so we can save when these fields are empty and they wont show invalid
=> optional urls

dist/index.cjs.js, dist/index.esm.js, package.json, src/lib/f5-utils.js, unit-tests/f5-utils.test.js
forgot one part of making f5 fields optional, this fixes
=> null check

dist/index.cjs.js, dist/index.esm.js, package.json, playground/src/App.js, src/components/forms/AtrackerForm.js, storybook/src/stories/Forms/AtrackerForm.stories.js
- added ability to disable atracker
- fixed name hover text
=> Issue 264: atracker enhancements

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/Buttons.js
needed to 
a) query the element on the page and be able to click it for testing
b) accessibility tree, so it is known that this is a button
=> open now has role=button

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/ClusterForm.js, src/components/forms/KeyManagementForm.js, src/components/forms/SecurityGroupForm.js
=> fixes for those forms

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/VpnServerRouteForm.js, src/components/index.js, storybook/src/stories/Forms/VpnServerRouteForm.stories.js
=> VpnServerRouteForm

dist/index.cjs.js, dist/index.esm.js, src/components/forms/ClusterForm.js, src/components/forms/F5VsiForm.js, src/components/forms/F5VsiTemplateForm.js, src/components/forms/KeyManagementForm.js, src/components/forms/NetworkingRulesOrderCard.js, src/components/forms/SubnetForm.js, src/components/forms/SubnetTierForm.js, src/components/forms/SubnetTileForm.js, src/components/forms/TransitGatewayForm.js, src/components/forms/VpeForm.js, src/components/forms/WorkerPoolForm.js, storybook/src/stories/Forms/AppIdForms.stories.js, storybook/src/stories/Forms/AtrackerForm.stories.js, storybook/src/stories/Forms/ClusterForm.stories.js, storybook/src/stories/Forms/F5VsiForm.stories.js, storybook/src/stories/Forms/F5VsiTemplateForm.stories.js, storybook/src/stories/Forms/KeyManagement.stories.js, storybook/src/stories/Forms/NetworkingRuleOrderCard.stories.js, storybook/src/stories/Forms/ObjectStorage/ObjectStorageForm.stories.js, storybook/src/stories/Forms/SecurityGroupForm.stories.js, storybook/src/stories/Forms/Subnets/SubnetTierForm.stories.js, storybook/src/stories/Forms/TransitGateway.stories.js, storybook/src/stories/Forms/VpeForm.stories.js, storybook/src/stories/Forms/WorkerPoolForm.stories.js
https://github.ibm.com/Jennifer-Valle/CRAIG/issues/242
remove required for vpc, resource_group, encryption_key, tmos_admin_password, byol_license_basekey to avoid null warning
=> issue 242: remove required for null warning

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/dns/DnsZoneForm.js, src/components/index.js, storybook/src/stories/Forms/DNS/DnsZoneForm.stories.js
https://github.ibm.com/Jennifer-Valle/CRAIG/issues/395
=> Issue395: DNS zone form

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/LogDNAForm.js, src/components/index.js, storybook/src/stories/Forms/LogDNAForm.stories.js
- added logdna form and stories
=> LogDNA Form Implementation

package.json, src/components/forms/EncryptionKeyForm.js
=> Rotation for Encryption Keys now default 1 mo

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/AtrackerForm.js, storybook/src/stories/Forms/AtrackerForm.stories.js
- added instance toggle
- added rg when instance true
- added plan when instance true
- added archive when instance true and logdnaEnabled is passed as prop
=> Atracker Form Updates

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/AppIdForm.js, src/components/forms/SecurityGroupForm.js, src/components/forms/VpcForm.js, src/components/forms/VsiForm.js, src/components/forms/VsiLoadBalancerForm.js
- vpc, vsi, sg forms now use field width smaller
- fixed alignment on appid modal 
- vsi load balancers now have private (nlb) public (ALB) on dropdowns, saves to state as `public` and `private` only
=> Form Enhancements

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/EmptyResourceTile.js, src/lib/button-utils.js, src/lib/empty-resource-tile.js, src/lib/index.js, storybook/src/stories/Other/EmptyResourceTile.stories.js, unit-tests/empty-resource-tile.test.js
- refactored empty resource tile
- removed instructions prop, no longer used
- 100ut
merge after #126
=> Craig 528: Empty Resource Tile Refactor

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/dns/DnsRecordForm.js
=> Craig 537: DNS resource type bug fix

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/Utils.js, src/components/forms/cbr/CbrContextForm.js, src/components/forms/cbr/CbrExclusionAddressForm.js, src/components/forms/cbr/CbrResourceAttributeForm.js, src/components/forms/cbr/CbrRuleForm.js, src/components/forms/cbr/CbrTagForm.js, src/components/forms/cbr/CbrZoneForm.js, src/lib/cbr-utils.js, src/lib/index.js, unit-tests/cbr-utils.test.js
- cleaned up all cbr forms
- fixed a bug causing title form titles to be the wrong size
=> CBR Cleanup

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, src/components/forms/AppIdForm.js, src/components/forms/AtrackerForm.js, src/lib/forms/atracker.js, src/lib/forms/index.js, storybook/src/stories/Forms/AppIdForms.stories.js, storybook/src/stories/Forms/AtrackerForm.stories.js, unit-tests/forms/atracker.test.js
- appid and atracker done
- drafting til chris' pr is in then i will merge and req rev
=> Craig 549, 553: appid and atracker

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/LogDNAForm.js
log dna tooltip will not go over nav bar now
=> fix logdna tooltip

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/LogDNAForm.js, src/components/forms/SysdigForm.js
Needed to add align to tooltip on SysdigForm too. When the screen was small cut off was happening due to the field adjusting to the screen size.
=> Craig 601: fix tooltip on SysdigForm

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/EventStreamsForm.js, src/lib/forms/event-streams.js, storybook/src/stories/Forms/EventStreamsForm.stories.js, unit-tests/forms/event-streams.test.js
=> Craig 556: Event Streams Form Refactor

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/RoutingTableForm.js, storybook/src/stories/Forms/RoutingTableForm.stories.js
=> routing table form refactor

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, playground/package-lock.json, src/components/forms/IamAccountSettingsForm.js, src/lib/forms/iam.js, storybook/package-lock.json, unit-tests/forms/iam.test.js
https://github.ibm.com/craig-automation/CRAIG/issues/558
=> Refractor: IAM

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/crud-form-pages/ObjectStorage.js, src/components/crud-form-pages/index.js, src/components/index.js
=> feat: obj storage template

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/crud-form-pages/VsiLoadBalancer.js, src/components/crud-form-pages/index.js, src/components/index.js, storybook/src/stories/Forms/VsiLoadBalancerForm.stories.js
https://github.ibm.com/craig-automation/craig/issues/625
create crud for page for vsi load balancer
clean up storybook story
=> vsi load balancer 

dist/index.cjs.js, dist/index.esm.js, package-lock.json, package.json, playground/package-lock.json, src/components/crud-form-pages/CloudDatabase.js, src/components/crud-form-pages/index.js, src/components/forms/CloudDatabaseForm.js, src/components/index.js, src/lib/forms/database.js, storybook/package-lock.json, unit-tests/forms/database.test.js
https://github.ibm.com/craig-automation/CRAIG/issues/682
create crud for page for ICD
=> ICD Page - Craig 682

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/EncryptionKeyForm.js
connected to issue 739 in CRAIG
=> Fixing Encryption Key Toggle bug

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/forms/SysdigForm.js
=> Reduced Sysdig tiers down to 'Graduated Tier'

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/crud-form-pages/ObjectStorage.js, src/components/forms/ObjectStorageBucketForm.js, src/components/forms/ObjectStorageForm.js, storybook/src/stories/Forms/ObjectStorage/ObjectStorageForm.stories.js
Removed an = in ObjectStorageBucketForm due to getting a 
> This condition will always return 'false' since JavaScript compares objects by reference, not value.
Error on my machine with ===
=> CRAIG 819: Add dropdown to select cos plan

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/Modals.js, storybook/src/stories/Modals/IcseModal.stories.js
Added size prop to IcseModal valid values are `xs`, `sm`, `md`, and `lg` and default value is `md`
=> Craig 800: Update IcseModal to accept size prop

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/crud-form-pages/Clusters.js, src/components/crud-form-pages/NetworkAcls.js, src/components/crud-form-pages/NoVpcTile.js, src/components/crud-form-pages/RoutingTables.js, src/components/crud-form-pages/SecurityGroups.js, src/components/crud-form-pages/Subnets.js, src/components/crud-form-pages/Vpc.js, src/components/crud-form-pages/Vpe.js, src/components/crud-form-pages/VpnGateways.js, src/components/crud-form-pages/VpnServers.js, src/components/crud-form-pages/Vsi.js, src/components/crud-form-pages/VsiLoadBalancer.js, src/components/crud-form-pages/no-secrets-manager-tile.css
Moved NoVpcTile from CRAIG to here so that the header still appears when the tile is shown
=> Craig 911: NoVpcTile

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/crud-form-pages/ClassicVlan.js
=> Update classic vlan page

dist/index.cjs.js, dist/index.esm.js, package.json, src/components/crud-form-pages/NoAclTile.js, src/components/crud-form-pages/Subnets.js
=> Craig 1067: Prevent Subnet creation if no ACLs have been created
